[theme]

# Primary accent for interactive elements
primaryColor = '#0D152D'

# Background color for the main content area
backgroundColor = '#223956'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#296492'

# Color used for almost all text
textColor = '#F8F9F6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"